name: Build and Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

env:
  BUCKET_NAME: team09-cicd-bucket
  PROJECT_NAME: studay
  DEPLOYMENT_GROUP_NAME: studay_cicd
  CODE_DEPLOY_APP_NAME: studay_cicd

jobs:
  # 작업의 이름
  build_and_test:
    # GitHub Actions 러너의 운영 체제
    runs-on: ubuntu-latest

    # 순차적으로 실행될 단계들을 정의하는 섹션
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML_CONTENT }}" > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML_CONTENT }}" > src/main/resources/application-dev.yml
          echo "${{ secrets.APPLICATION_YML_CONTENT }}" > src/main/resources/application-oauth.yml
      - name: Build with gradle
        run: ./gradlew build

